### ISSUE TITLE
Incorrectly parsing documents

### ISSUE THREAD

**Issue by hellopablo** [sylzys/TypoFixr#1]
Hi,

I'm experiencing a weird issue where this plugin incorrectly parses documents.

It, seemingly randomly, will just replace a random section of the document with one of my corrections.

I'm not entirely sure what info to provide, but here's the latest example. My user config looks like this:

``` javascript
{
    "replacements": {
        "dumpandide":"dumpanddie",
        "dumapnddie":"dumpanddie",
        "dumapdndie":"dumpanddie"
    }
}
```

One of my JS files begins like this:

``` javascript
/**
 * This module allows a user to add a new radio station to their list
 */
define(['global/auth'], function(auth) {
    // Code in here
});
```

When I hit save, TypoFixr leaves me with:

``` javascript
dumpanddies module allows a user to add a new radio station to their list
 */
define(['global/auth'], function(auth) {
    // Code in here
});
```

Obviously this is a weird and incorrect replacement! I don't know Python so, despite trying, have failed to narrow it down in the plugin's source code, an incorrect regex perhaps? Or maybe I'm doing something wrong?

I'm using ST3, build 3065.

This is only an example, it happens in other files, too - namely PHP files, although I don't think the actual file type/syntax is accounted for.

**Comment by brocoli** [comment]
I've had the same problem when I defined a typo fix like this:

``` javascript
[...]
";ocal": "local",
"buidler": "builder",
[...]
```

after this, there was a particular instance of "local" that kept being substituted by "builder". Removing the ";ocal" replacement didn't help, but removing that particular substitution and then reinstalling the package made it stop.
